# Rust code style: standard project config
# https://rust-lang.github.io/rustfmt/

edition = "2021"
max_width = 100
tab_spaces = 4

# Imports: group std, then external, then crate
group_imports = "StdExternalCrate"
imports_granularity = "Crate"

# Consistency
reorder_impl_items = true
format_strings = true
use_small_heuristics = "Default"
